billmanager/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'bills.views.dashboard', name='dashboard'),
    url(r'^create/$', 'bills.views.create', name='create'),
    # url for all bills /bills/
    url(r'^bills/(\d+)/$', 'bills.views.show_bill', name='bill'),
    url(r'^bills/(\d+)/delete/$', 'bills.views.delete_bill', name='delete_bill'),
    url(r'^bills/(\d+)/paid/$', 'bills.views.mark_bill_as_paid', name='mark_bill_paid'),
    url(r'^bills/(\d+)/unpaid/$', 'bills.views.mark_bill_as_unpaid', name='mark_bill_unpaid'),
    url(r'^users/(\d+)/add/$', 'bills.views.add_user', name='add_user'),
    url(r'^login/$', 'bills.views.login', name='login'),
    url(r'^register/$', 'bills.views.register', name='register'),
    url(r'^logout/$', 'bills.views.logout', name='logout'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

bills/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Bill(models.Model):
	creator = models.ForeignKey(User)
	item = models.CharField(max_length=200)
	amount = models.DecimalField(max_digits=9, decimal_places=2)
	due_date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
	message = models.TextField(max_length=4000, blank=True, null=True)
	recipient = models.ForeignKey(User, related_name='user', blank=True, null=True)

	# Hidden Fields
	creation_date = models.DateTimeField(auto_now=True)
	recipient_marked_paid = models.BooleanField(default=False)
	creator_marked_paid = models.BooleanField(default=False)

	def __unicode__(self):
		return self.item



class UserProfile(models.Model):
	# required
	user = models.OneToOneField(User, unique=True)

	friends = models.ManyToManyField(User, related_name='friends')

class Friendship(models.Model):
	from_friend = models.ForeignKey(User, related_name='friend_set')
	to_friend = models.ForeignKey(User, related_name='to_friend_set')

	def __unicode__(self):
		return u'%s, %s' % (
			self.from_friend.email,
			self.to_friend.email)

	class Meta:
		unique_together = (('to_friend', 'from_friend'),)

bills/forms.py
from django import forms
from django.forms import ModelForm
from bills.models import *
from bills.form_fields import *

class CreateBillForm(ModelForm):
	recipient = forms.EmailField(max_length=100)
	class Meta:
		model = Bill
		fields = ('item', 'amount', 'due_date', 'message')
		exclude = ('creator', )

	def clean(self, *args, **kwargs):
		return super(CreateBillForm, self).clean(*args, **kwargs)

class DeleteBillForm(forms.ModelForm):
	class Meta:
		model = Bill
		fields = []

class MarkBillForm(forms.ModelForm):
	class Meta:
		model = Bill
		fields = []

class LoginForm(forms.Form):
	username = forms.EmailField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput(render_value=False),max_length=100)

class RegisterForm(forms.Form):
	username = forms.EmailField(max_length=100)
	password = forms.CharField(widget=forms.PasswordInput(render_value=False),max_length=100)
	first_name = forms.CharField(max_length=24)
	last_name = forms.CharField(max_length=24)

bills/views.py
from bills import utils
from bills.emails import *
from bills.models import *
from bills.forms import *
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.shortcuts import render, render_to_response, get_object_or_404
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

def login(request):
	
	form = LoginForm()
	message = ''

	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			# successful authentication
			if user.is_active:
				auth_login(request, user)
				return HttpResponseRedirect('/')

	csrfContext = RequestContext(request, {'form': form, 'message': message})
	return render_to_response('login.html', csrfContext, RequestContext(request))

def logout(request):
	form = LoginForm()
	message = 'You have successfully logged out'

	auth_logout(request)

	csrfContext = RequestContext(request, {'form': form, 'message': message})
	return render_to_response('login.html', csrfContext, RequestContext(request))

def register(request):

	errors = {}

	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		first_name = request.POST['first_name']
		last_name = request.POST['last_name']

		# Check if user exists
		if User.objects.filter(username=username).count():
			errors = {'username': 'User already exists'}

		else:
			new_user = User.objects.create_user(username=username, password=password)
			new_user.first_name = first_name
			new_user.last_name = last_name
			new_user.save()

			# authenticate user
			new_user = authenticate(username=username, password=password)

			if new_user.is_active:
				auth_login(request, new_user)
				# TODO: include some message for new users
				return render_to_response('dashboard.html')

			else:
				errors = {'login': 'Something went wrong'}

	form = RegisterForm()
	csrfContext = RequestContext(request, {'form': form, 'errors': errors})
	return render_to_response('register.html', csrfContext)


@login_required
def dashboard(request):
	bill_list = Bill.objects.filter(creator=request.user).order_by('-due_date')[:5]
	my_bill_list = Bill.objects.filter(recipient=request.user).order_by('-due_date')[:5]
	return render_to_response('dashboard.html', {
		'bill_list': bill_list,
		'my_bill_list': my_bill_list
		}, RequestContext(request))

@login_required
def create(request):
	if request.method == 'POST':
		form = CreateBillForm(request.POST)
		if form.is_valid():
			bill = form.save(commit=False)
			bill.creator = request.user
			bill.recipient = utils.get_or_create_user(form.cleaned_data['recipient'])
			bill.save()
			send_new_bill_notification(bill)
			return HttpResponseRedirect('/')
	else:
		form = CreateBillForm()

	friends = [ friendship.to_friend
		for friendship in request.user.friend_set.all() ]

	csrfContext = RequestContext(request, {
		'form': form,
		'friends': friends })
	return render_to_response('create.html', csrfContext, RequestContext(request))

def show_bill(request, id):

	# check if bill exists
	bill = get_object_or_404(Bill, pk=id)

	# check if user has access to the bill
	if bill.creator == request.user or bill.recipient == request.user:
		return render_to_response('bill.html', {'bill': bill}, RequestContext(request))

	else:  # user does not have persission to see the bill
		form = LoginForm()
		message = ''
		csrfContext = RequestContext(request, {'form': form, 'message': message})
		return render_to_response('login.html', csrfContext, RequestContext(request))
	
@login_required
def delete_bill(request, id):

	message = ''

	# check if bill exists
	bill_to_delete = get_object_or_404(Bill, pk=id)

	form = DeleteBillForm(request.POST, instance=bill_to_delete)

	user_is_authorized_to_delete_bill = False

	if bill_to_delete.creator.pk == request.user.pk:
		user_is_authorized_to_delete_bill = True

	if user_is_authorized_to_delete_bill:
		if form.is_valid:  # check csrf
			bill_to_delete.delete()
			return HttpResponseRedirect("/")
		
		else:
			message = 'Unable to delete bill'
	else:
		message = 'You do not have permission to delete this bill'


	csrfContext = RequestContext(request, {
		'delete_form': form, 
		'bill': bill_to_delete, 
		'message': message})
	return render_to_response('bill.html', csrfContext, RequestContext(request) )


@login_required
def add_user(request, id):

	# check if user exists
	user_to_add = get_object_or_404(User, pk=id)

	current_user = request.user
	friendship = Friendship(from_friend=current_user, to_friend=user_to_add)
	friendship.save()

	return HttpResponseRedirect('/')

@login_required
def mark_bill_as_paid(request, id):
	bill_to_mark = get_object_or_404(Bill, pk=id)

	message = 'Unable to modify bill'

	# check if bill exists

	form = MarkBillForm(request.POST, instance=bill_to_mark)

	if form.is_valid:  # check csrf

		# user is the creator
		if bill_to_mark.creator.pk == request.user.pk:
			bill_to_mark.creator_marked_paid = True
			
		# user is the recipient
		elif bill_to_mark.recipient.pk == request.user.pk:
			bill_to_mark.recipient_marked_paid = True
				
		else:
			message = 'You do not have permission to modify this bill'

		bill_to_mark.save()
		return HttpResponseRedirect("/")

	csrfContext = RequestContext(request, {
		'mark_form': form, 
		'bill': bill_to_mark, 
		'message': message})
	return render_to_response('bill.html', csrfContext, RequestContext(request) )


@login_required
def mark_bill_as_unpaid(request, id):
	bill_to_mark = get_object_or_404(Bill, pk=id)

	message = 'Unable to modify bill'

	# check if bill exists

	form = MarkBillForm(request.POST, instance=bill_to_mark)

	if form.is_valid:  # check csrf

		# user is the creator
		if bill_to_mark.creator.pk == request.user.pk:
			bill_to_mark.creator_marked_paid = False
			
		# user is the recipient
		elif bill_to_mark.recipient.pk == request.user.pk:
			bill_to_mark.recipient_marked_paid = False
				
		else:
			message = 'You do not have permission to modify this bill'

		bill_to_mark.save()
		return HttpResponseRedirect("/")

	csrfContext = RequestContext(request, {
		'mark_form': form, 
		'bill': bill_to_mark, 
		'message': message})
	return render_to_response('bill.html', csrfContext, RequestContext(request) )

bills/templates/base.html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>{% block title %}{% endblock %}</title>

	<link href="/static/css/main.css" rel="stylesheet" media="screen" />
	<link href="/static/css/font-awesome.min.css" rel="stylesheet" >
	{% block css %}{% endblock %}
	
	<script type="text/javascript" src="/static/js/jquery.js"></script>
	<script type="text/javascript" src="/static/js/app.js"></script>
	{% block js %}{% endblock %}
	
</head>

<body>
	{% block header %}{% endblock %}
	{% block content %}{% endblock %}
	{% block footer %}{% endblock %}
</body>
</html>

bills/templates/bill.html
{% extends 'default.html' %}

{% block title %}New Bill{% endblock %}

{% block css %}
	<link href="/static/css/bill.css" rel="stylesheet" media="screen" />
{% endblock %}

{% block content %}

{% if bill %}
	<div class="bill modal">
		<aside><a href="/">Back to Dashboard</a></aside>
		<h2>{{ bill.item }}</h2>
		<p>Created on: {{ bill.creation_date}}</p>
		<h2>${{ bill.amount}}</h2>
		{% if bill.message %}<p>{{ bill.message }}</p>{% endif %}
		<date>{{ bill.due_date}}</date>
		<p>{{ bill.recipient}}</p>

		{% if bill.creator.pk == request.user.pk %}

			{% if bill.creator_marked_paid %}
				<a class="button" href="{% url mark_bill_unpaid bill.id %}">{{bill.recipient}} has not paid this</a>
			{% else %}
				<a class="button" href="{% url mark_bill_paid bill.id %}">{{bill.recipient}} has paid this</a>
			{% endif %}
			<a class="button delete confirm-delete" href="{% url delete_bill bill.id %}">Delete this bill</a>
		{% else %}
			<a class="button" href="#">I paid this</a>
		{% endif %}
	</div>
{% else %}

	<h1>There was a problem displaying the bill</h1>

{% endif %}

{% endblock %}

bills/templates/create.html
{% extends 'default.html' %}

{% block title %}New Bill{% endblock %}

{% block css %}
	<link href="/static/css/create.css" rel="stylesheet" media="screen" />
{% endblock %}

{% block content %}
<div class="main-form">

	<form action="/create/" method="post"> {% csrf_token %}
		{{ form.non_field_errors }}

		<div class="top form-row clear">
			<div class="field-wrap item">
				{{ form.item.errors }}
				<label for="id_item">Item</label>
				{{ form.item }}
			</div>

			<div class="field-wrap amount">
				{{ form.amount.errors }}
				<label for="id_amount">Amount</label>
				{{ form.amount }}
			</div>

			<div class="field-wrap due-date">
				{{ form.due_date.errors }}
				<label for="id_due_date">Due Date</label>
				{{ form.due_date }}
			</div>
		</div>

		<div class="bottom form-row clear">
			<div class="field-wrap message">
				{{ form.message.errors }}
				<label for="id_message">Message</label>
				<input id="id_message" type="text" name="message" maxlength="1000">
			</div>

			<div class="field-wrap message quickselect">
				{{ form.recipient.errors }}
				<label for="id_recipient">Recipient</label>
				{{ form.recipient }}
				{% for friend in friends %}
					<a href="#" data-user-id="{{ friend.id }}">{{ friend.username }}</a>
				{% endfor %}
			</div>
		</div>

		<input type="submit" value="Submit" />
	</form>

</div>
{% endblock %}

bills/templates/dashboard.html
{% extends 'default.html' %}

{% block title %}Dashboard{% endblock %}

{% block css %}
	<link href="/static/css/dashboard.css" rel="stylesheet" media="screen" />
{% endblock %}

{% block content %}

	<div class="main-content">

		<div class="table sent-list">
			<header></header>
			<div class="row buttons new-bill clear">
				<a class="button" title="Request a new payment" href="{% url create %}"><i class="icon-plus"></i> New Bill</a>
			</div>
			
				
			{% if bill_list %}
				{% for bill in bill_list %}
					<div class="row-container {% if bill.creator_marked_paid %}paid{% endif %}">
						<div class="row content clear">
							<span class="block amount dollars">${{ bill.amount}}</span>
							<div class="block item">
								<div class="name">{% if bill.creator_marked_paid %}PAID - {% endif %}{{ bill.item }}</div>
								{% if bill.message %}
								<p class="description">{{ bill.message }}</p>
								{% endif %}
							</div>
							<span class="block duedate">{{ bill.due_date}}</span>
						</div>
						<div class="row actions clear ">
							{% if bill.creator_marked_paid %}
								<a class="mark-paid" href="{% url mark_bill_unpaid bill.id %}"><i class="icon-check"></i> Mark as unpaid</a>
							{% else %}
								<a class="mark-paid" href="{% url mark_bill_paid bill.id %}"><i class="icon-check-empty"></i> Mark as paid</a>
							{% endif %}
							<a class="delete button confirm-delete" href="{% url delete_bill bill.id %}">Delete</a>
							<a class="show-details" href="{% url bill bill.id %}">See details <i class="icon-share"></i></a>
						</div>
					</div>
				{% endfor %}
			{% else%}
				<div class="row buttons no-bills clear">
					<span>You haven't created any bills yet</span>	
				</div>
			{% endif %}
			
		</div>

		<!--
		<table class="content-blur">
			<thead>
				<tr>
					<th>Amount</th>
					<th>Item</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				{% if my_bill_list %}
					{% for bill in my_bill_list %}
						<tr data-href="{% url bill bill.id %}">
							<td>${{ bill.amount}}</td>
							<td>
								<span>{{ bill.item }}</span>
								{% if bill.message %}<p>{{ bill.message }}</p>{% endif %}
							</td>
							<td>{{ bill.due_date}}</td>
						</tr>
					{% endfor %}
				{% else%}
					<tr>
						<td>Congrats, you're all paid up!</td>
						<td></td>
						<td></td>
					</tr>
				{% endif %}
			</tbody>
		</table>
	-->
	</div>
{% endblock %}

bills/templates/default.html
{% extends 'base.html' %}


{% block header %}

	<header class="header-primary">
		<nav>
			{% if request.user.is_authenticated %}
			<a class="button">{{ request.user.username }}</a>
			{% endif %}
			<a class="button" href="{% url dashboard %}">Home</a>
			<a class="button" href="{% url create %}">+ New Bill</a>
			<a class="button logout" href="{% url logout %}">Logout</a>
		</nav>
	
	</header>


{% endblock %}


{% block content %}
	<div class="body">

	</div>
{% endblock %}


{% block footer %}
	<footer class="body">

	</footer>
{% endblock %}

bills/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block css %}
	<link href="/static/css/login.css" rel="stylesheet" media="screen" />
{% endblock %}



{% block content %}


<div class="login modal">

	{% if form.errors %}
		<p>Your username and password didn't match. Please try again.</p>
	{% endif %}

	<form method="post" action="/login/">
	{% csrf_token %}

		<div class="field-wrap">
			<input id="id_username" type="text" name="username" maxlength="100" placeholder="you@email.com" autofocus="true">
		</div>
		<div class="field-wrap">
			<input id="id_password" type="password" name="password" maxlength="100" placeholder="************" >
		</div>
	

	<input type="submit" value="login" />
	<input type="hidden" name="next" value="{{ next }}" />
	</form>

</div>

{% endblock %}

bills/templates/register.html
{% extends "base.html" %}

{% block content %}

{% if errors.username %}
	<div class="error">{{ errors.username }}</div>
{% endif %}

{% if errors.login %}
	<div class="error">{{ errors.login }}</div>
{% endif %}

<form method="post" action="/register/">
{% csrf_token %}
<table>
<tr>
	<td>* Your first name (to help your friends identify you)</td>
	<td>{{ form.first_name }}</td>
</tr>
<tr>
	<td>Your last name</td>
	<td>{{ form.last_name }}</td>
</tr>
<tr>
	<td>* Email Address</td>
	<td>{{ form.username }}</td>
</tr>
<tr>
	<td>* Password</td>
	<td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="register" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}